//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registe_loginDeskapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlog
    {
        public int user_ids { get; set; }
        public string Username { get; set; }
        public string Passwords { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Phone_number { get; set; }
        public string City { get; set; }
    }
}
